### ISSUE TITLE
compile failed in ubuntu 20.04 (gcc version 11.3.0)

### ISSUE THREAD

**Issue by longcongduoi** [asyncpp/asyncpp-uring#2]
In file included from  asyncpp/asyncpp-uring/examples/uring-info.cpp:1:
asyncpp-uring/include/asyncpp/uring/capability_set.h:15:19: error: ‘constexpr’ static data member ‘no_parse_tag’ must have an initializer
   15 |                 } no_parse_tag;

**Comment by Thalhammer** [comment]
Word of caution ahead: Unlike the main library which I use in production, this extension isn't really used anywhere outside some toy projects, so there might be more bugs hideing.

I tried compiling it with ubuntu 22.04 & gcc11 and added a bunch of fixes to make it work, along with support for older liburing versions, which you'll probably run into as well.

Feel free to try the work in #3 and let me know if you find other issues.
