### ISSUE TITLE
Can't build uring-info.cpp 

### ISSUE THREAD

**Issue by lordvictory** [asyncpp/asyncpp-uring#4]
Am building on x86_64 Unbuntu 23.10 g++ 13.2.0

Can't get past including the 2 header files.  I get the following compile failure message:

/mnt/hgfs/idx5/tests/coro/inc/asyncpp/uring/io_service.h: In instantiation of ‘auto asyncpp::uring::io_service::do_call(Args&& ...) [with auto PrepareFN = io_uring_prep_poll_remove; Args = {void*}]’:
/mnt/hgfs/idx5/tests/coro/inc/asyncpp/uring/io_service.h:560:89:   required from here
/mnt/hgfs/idx5/tests/coro/inc/asyncpp/uring/io_service.h:474:34: error: invalid conversion from ‘void*’ to ‘__u64’ {aka ‘long long unsigned int’} [-fpermissive]
  474 |                         PrepareFN(sqe, std::forward<Args>(args)...);
      |                         ~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                  |
      |                                  void*

Haven't ever used anything from this toolkit before...but seems like something might need updating.  Not sure where to go from here?

**Comment by Thalhammer** [comment]
Yes seems like in axboe/liburing@d84c29b19ed0b130000619cff40141bb1fc3615b the function signature was changed (and some of the functions changed back again later).
Liburing does that from time to time, which is really annoying imho.
I pushed a commit (ff99c6702a70f0f3567a9a161a4181e09f2a4457) that hopefully catches all the variants, let me know if it solves your issue.

**Comment by Thalhammer** [comment]
I am going to close this due to inactivity, but feel free to reopen if the issue still persists.
